openapi: 3.0.1
info:
  title: Bastos Run Coach API
  description: API do Time Bastos para GPT com integração externa
  version: 1.0.0
servers:
  - url: https://bastosruncoach.onrender.com
paths:
  /ultimotreino:
    get:
      summary: Retorna o último treino
      operationId: getUltimoTreino
      responses:
        '200':
          description: Último treino retornado
  /analisar:
    post:
      summary: Analisa uma atividade
      operationId: analisarTreino
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                distancia:
                  type: number
                ritmo:
                  type: string
              required:
                - distancia
                - ritmo
      responses:
        '200':
          description: Análise retornada
  /sincronizar:
    get:
      summary: Inicia o login via Strava
      operationId: iniciarSincronizacao
      responses:
        '200':
          description: Redirecionamento iniciado
